### PR TITLE
Fixed #94 - Revised startup checks to look for enterprise policies, and set them accordingly.

### LINKED ISSUE #94: Telemetry events are no longer sent after setting a disable "DNSOverHTTPS" Enterprise Policy and restarting the browser
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Nightly 71.0a1, Build ID 20190918215055
- Firefox Dev Edition 70.0b7, Build ID 20190916074538
- Firefox unbranded Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.6-signed-testing.xpi add-on is installed.
- A disable "DNSOverHTTPS" policy is set.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:config".
2. Add the "doh-rollout.enabled" boolean pref with the "true" value.
3. Restart the browser and navigate to "about:telemetry".
4. Observe the "Events" section.

[Expected result]:
- A "disable_doh" telemetry event is displayed after a restart.

[Actual result]:
- No telemetry events are displayed after a restart.

[Notes]:
- The "enable_doh" telemetry event is not sent after changing the policy to enable "DNSOverHTTPS" if it was previously disabled.
- This issue is only reproducible when setting up a policy using a policies.json file and not the Local Group Policy Editor on Windows.
- I have attached a screen recording of the issue:
restart_ping

### PR DESCRIPTION
**Pull request by maxxcrawford**
Note: No conflicts!  ~This will conflict with the other open PR #119~ 

**Telemetry Updates:**
This commit overhauls how policy checks are sent, including revising the telemetry events slightly. Rather than just on `startup` and `netChange`, it now includes the following:
- `first_run`: Runs the very first time on startup in cases when an enterprise policy is set. This doesn't run if an enterprise policy is not detected _(Normal `startup` event runs instead)_. 
- `shouldRunHeuristics_mismatch`: This runs when during any normal heuristics check, and detects that following conditions: user has not opted out, the cached version of TRR.mode has changed from what the current mode is and DoH is not disabled. 

Additionally, the huestiric results checks across the various areas and returns either a "disable_doh" or "enable_doh". To remove false positives, the `checkEnterprisePolicies` [function](https://github.com/mozilla/doh-rollout/blob/94-enterprise-policy/src/experiments/heuristics/api.js#L68-L69) also returns `no_policy_set`. As this isn't an explicit reason to disable DoH, it doesn't change functionality outside of the new logic to check Policies first. 

**Expected Results:**
- If a user has a value set for `network.trr.mode`, and an enterprise policy set, the policy is respected above all else. 
- If a policy is detected, a specific telemetry event is fired, in addition to enabling/disabling DoH.

### CODE REVIEW

**Comment by tdsmith** [comment]
I think the docs need to catch up:

```diff
diff --git a/docs/telemetry.md b/docs/telemetry.md
index 0a19285..6551033 100644
--- a/docs/telemetry.md
+++ b/docs/telemetry.md
@@ -17,3 +17,3 @@ The event extras include:
 * `thirdPartyRoots`: if third-party roots are included in the Firefox trust store
-* `policy`: if Firefox enterprise policies are active and DoH is not explicitly allowed
+* `policy`: if Firefox enterprise policies are active and DoH is disabled
 * `evaluateReason`: why heuristics were evaluated
```

Otherwise, makes sense to me.

File: src/background.js [hunk 1]
```diff
@@ -193,43 +194,102 @@ const rollout = {
...
+    // This runs only on the FIRST time that add-on is enabled and if the stored pref
+    // mismatches the current pref (Meaning something outside of the add-on has changed it)
+
     if (
       await browser.experiments.preferences.prefHasUserValue(
         TRR_MODE_PREF)
     ) {
-      // TODO: Add telemtery ping for user who already has pref on DoH
+      let curMode = await browser.experiments.preferences.getUserPref(TRR_MODE_PREF, 0);
+      curMode = await this.decodeTrrMode(curMode);
```
Comment (jonathanKingston) [inline src/background.js]: It would be clearer to set this to it's own var. Can we make the response value functional code in disabling doh?

Comment (jonathanKingston) [reply src/background.js]: For example it seems we only use this function to send to telemetry, whatever we use elsewhere might get out of date or subtly different.

**Comment by maxxcrawford** [comment]
@tdsmith @jonathanKingston Added telemetry documentation describing the updates. If this doesn't work, let's file a separate issue.

File: docs/telemetry.md [hunk 2]
```diff
@@ -6,16 +6,25 @@ All events are sent with category `doh`.
...
 
+The event value can be the following:
+- `enable_doh`: Safe to enable DoH
+- `disable_doh`: DoH should not be enabled based on heuristics
+- Other:
+  - `prefHasUserValue`: User already have a value for `network.trr.mode`, so the add-on will not modify DoH settings. 
+  - `doorhangerDecline`: User clicked no on the doorhanger, opting out of the study.
+  - `userModified`: The user manually updated the `network.trr.mode`, so the study has been disabled.
+
 The event value is either `enable_doh` or `disable_doh`, reflecting the result of the evaluation.
```
Comment (tdsmith) [inline docs/telemetry.md]: This bottom line should be deleted, right?

Comment (tdsmith) [reply docs/telemetry.md]: I see you already did that; thanks!
