### PR TITLE
Fixed #72 - Revised netChange event fire to only fire when applicable. 

### LINKED ISSUE #72: Multiple "netChange" telemetry events are sent on Firefox 69
[Notes]:
- On Linux the behavior is different, after a network change, no telemetry events are displayed.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Unbranded Release 69.0, Build ID 20190827005903
- Firefox Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.5rc2-signed.xpi add-on is installed.
- Have the "doh-rollout.enabled" boolean pref set to "true".
- DoH is enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Disconnect and reconnect to the internet.
3. Navigate to about:telemetry and observe the events.

[Expected result]:
- One DoH heuristics event is displayed with the "evaluateReason:netChange" value.

[Actual result]:
- Multiple pings (2-3) are displayed.

[Additional Notes]:
- I have attached a screen recording of the issue:
multiple_net

### PR DESCRIPTION
**Pull request by maxxcrawford**
Now it only fires netChange events when both linkStatusKnown and isLinkUp are true. I also reverted sleep timeout to 5s, as this works properly now, and won't fire the telemetry event without proper logic.

### CODE REVIEW

**Comment by nhi-nguyen** [comment]
@ddragana or @valenting: could one of you review this change, please?

File: src/experiments/netChange/api.js [hunk 1]
```diff
@@ -31,17 +31,16 @@ var netChange = class netChange extends ExtensionAPI {
...
-                  last_event = Date.now();
-                  fire.async(data);
-                }
-
-                if (data === "changed") {
-                  // We will coalesce event that are less than 30s apart.
-                  if ( Date.now() - last_event > 30000 &&  gNetworkLinkService.linkStatusKnown && gNetworkLinkService.isLinkUp) {
-                    last_event = Date.now();
-                    fire.async(data);
+                if (netChangeWaiting == false) {
```
Comment (valenting) [inline src/experiments/netChange/api.js]: Not sure on JS code style, but returning early
```
if (netChangeWaiting) {
   return;
}
```
seems much nicer. Same for data != changed/up
Not a big deal though.
