### PR TITLE
Fixed #114 - Revised doorhanger events

### LINKED ISSUE #114: [Regression] The doorhanger is no longer displayed when focusing another tab and switching back
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Nightly 71.0a1, Build ID 20190926094200
- Firefox Dev Edition 70.0b9, Build ID 20190923154733
- Firefox unbranded Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.8-signed-testing.xpi add-on is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:config".
2. Add the "doh-rollout.enabled" boolean pref with the "true" value.
3. Focus another tab.
4. Switch back to the previous tab and observe the behavior.

[Expected result]:
- The DoH doorhanger notification is displayed.

[Actual result]:
- The DoH doorhanger notification is no longer displayed.

[Notes]:
- The issue is not reproducible using the 0.0.6 version of the add-on.
- The "enable_doh" telemetry event is sent and the "network.trr.mode" pref is set to "2".
- I have attached a screen recording of the issue:
no_doorhanger

### PR DESCRIPTION
**Pull request by maxxcrawford**
This PR overhauls the doorhanger interactions.

Note: **If the doorhanger has been shown, DoH has been enabled.** Events mentioned further are specific to the doorhanger logic, not enabling/disabling DoH. 

**Expected results:**
- On both startup and netchange events the doorhanger will show if: 
  - Heuristics determine DoH can be enabled (which has its own checks) 
  - User has not interacted with the doorhanger (Clicked "OK, Got It", "Disable Protection" or clicked the ESC key) yet

Once the user has opted in or out, the door hanger will not be shown again. 

**Edge cases:**
- If the user closes the tab with the doorhanger shown or quits the browser entirely, no event occurs. The doorhanger will not be shown again until the next startup or netchange event, and the notification will display on whichever tab is active. 
- Switching to a new tab away from the active notification will not trigger any events or dismiss the notification 
- Clicking learn more link will not trigger any events or dismiss the notification

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -206,10 +235,14 @@ const rollout = {
       log("onConnectionChanged");
       // Only run the heuristics if user hasn't explicitly enabled/disabled DoH
       let shouldRunHeuristics = await stateManager.shouldRunHeuristics();
+      let shouldShowDoorhanger = await stateManager.shouldShowDoorhanger();
+
       if (shouldRunHeuristics) {
         const netChangeDecision = await rollout.heuristics("netChange");
         if (netChangeDecision === "disable_doh") {
           await stateManager.setState("disabled");
+        } else if (shouldShowDoorhanger) {
```
Comment (maxxcrawford) [inline src/background.js]: Adds the same logic that the `onReady` uses

File: src/background.js [hunk 2]
```diff
@@ -251,28 +284,14 @@ const rollout = {
...
-        okAccessKey: browser.i18n.getMessage("doorhangerButtonOkAccessKey"),
-        cancelLabel: browser.i18n.getMessage("doorhangerButtonCancel"),
-        cancelAccessKey: browser.i18n.getMessage("doorhangerButtonCancelAccessKey"),
-      });
-
-      await stateManager.rememberDoorhangerShown();
-
-    // If the doorhanger doesn't need to be shown and the heuristics
-    // say to enable DoH, enable it
+      await stateManager.showDoorHangerAndEnableDoH();
```
Comment (maxxcrawford) [inline src/background.js]: Rolled this function (as it is now used twice) into its own function. Robust function names!

File: src/experiments/doorhanger/api.js [hunk 3]
```diff
@@ -58,17 +58,6 @@ class DoorhangerEventEmitter extends EventEmitter {
 
     let learnMoreURL = Services.urlFormatter.formatURL("https://support.mozilla.org/%LOCALE%/kb/firefox-dns-over-https");
 
-    let doorhangerEvents = event => {
```
Comment (maxxcrawford) [inline src/experiments/doorhanger/api.js]: Removed previous `onDismissed` event, which was causing the root issue of #114

**Comment by jonathanKingston** [comment]
SGTM thanks
