### PR TITLE
Fixed 94 - Removed logic to only check for policies/userPref on first run

### LINKED ISSUE #94: Telemetry events are no longer sent after setting a disable "DNSOverHTTPS" Enterprise Policy and restarting the browser
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Nightly 71.0a1, Build ID 20190918215055
- Firefox Dev Edition 70.0b7, Build ID 20190916074538
- Firefox unbranded Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.6-signed-testing.xpi add-on is installed.
- A disable "DNSOverHTTPS" policy is set.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:config".
2. Add the "doh-rollout.enabled" boolean pref with the "true" value.
3. Restart the browser and navigate to "about:telemetry".
4. Observe the "Events" section.

[Expected result]:
- A "disable_doh" telemetry event is displayed after a restart.

[Actual result]:
- No telemetry events are displayed after a restart.

[Notes]:
- The "enable_doh" telemetry event is not sent after changing the policy to enable "DNSOverHTTPS" if it was previously disabled.
- This issue is only reproducible when setting up a policy using a policies.json file and not the Local Group Policy Editor on Windows.
- I have attached a screen recording of the issue:
restart_ping

### PR DESCRIPTION
**Pull request by maxxcrawford**
Fixed #94 

Also added additional logic to check Heuristics if a user had a policy set and then removed it.

To check, have a policy in place that disables DoH, run the addon and then reload the add-on. Before, it would only send one telemetry event. Now, it runs each time on "startup".

Also added logic to test for a policy set that doesn't reference DoH. Test it using this policy file: 
[policies-NoMentionDoH.json.zip](https://github.com/mozilla/doh-rollout/files/3697950/policies-NoMentionDoH.json.zip)

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -228,12 +228,10 @@ const rollout = {
     switch (policyEnableDoH) {
     case "enable_doh":
       log("Policy requires DoH enabled.");
-      await stateManager.setState("enabled");
       browser.experiments.heuristics.sendHeuristicsPing(policyEnableDoH, results);
       break;
     case "disable_doh":
       log("Policy requires DoH to be disabled.");
-      await stateManager.setState("disabled");
```
Comment (nhi-nguyen) [inline src/background.js]: This is problematic. `checkEnterprisePolicies()` can return `"disable_doh"` when the policy doesn't mention DoH at all. We do want to disable DoH in that case, removing that line affects that logic.

Comment (maxxcrawford) [reply src/background.js]: If their policy is disabled, it would set the trr.mode to 5, but the setState will override it to 0. Do we need to add more logic to the API for policy detection?

Comment (nhi-nguyen) [reply src/background.js]: This could be solved by adding the two lines back in, but put a conditional around each line: we only set enable/disable if user hasn't set trr.mode.... A few lines above, we already check for that, so we can only get here is user hasn't set trr.mode -> it's safe to add the lines back in.
