### PR TITLE
Fixed #152  – Sets local storage pref to remember that user has opted out of study manually

### LINKED ISSUE #152: DoH is re-enabled after disabling it from "about:preferences" and restarting the browser 3 times
**[Notes]:**
- This issue is only reproducible with the latest `doh_roll-out-1.0.2-signed.xpi` build.
- This is also reproducible using Firefox Release 70.0.
- This issue is reproducible using the provided Normandy recipe via Normandy Devtools as well as using a recipe from the Stage environment.
- This issue is reproducible with both **"default"** and **"user"** preference types.

**[Affected versions]:**
- Firefox Release 69.0.3 (Build ID: 20191009172106)

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- The 1.0.2 add-on is installed.
- The `doh-rollout.enabled` pref is set as `true` by a Normandy recipe. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites.
2. Click the "OK, Got It" option from the notification.
3. Navigate to "about:preferences#general" - Network Settings section.
4. Click the "Settings" button.
5. Uncheck the "Enable DNS Over HTTPS" checkbox.
6. Click the "OK" button.
7. Close and open the browser 3 times.
8. Navigate to "about:config" page and observe the value of the "network.trr.mode" pref.

**[Expected result]:**
- The value of the pref is "0".

**[Actual result]:**
- The value of the pref is "2" and the DoH notification is displayed again.

**[Additional Notes]:**
- Please see the attached video:

dns

### PR DESCRIPTION
**Pull request by maxxcrawford**
### To verify: 

- Install add-on and turn DoH on per normal directions
- Click "OK" when presented with door hanger
- Confirm `network.trr.mode` is set to `2`
- Disable DoH from the about:preferences Network dialog box 
- Confirm `network.trr.mode` is set to `0`
- Restart browser. Remember to run Normandy commands each time on start-up. 
- Confirm `network.trr.mode` is set to `0` after 2+ restarts

### CODE REVIEW

**Comment by maxxcrawford** [comment]
Test XPI File: [doh_roll-out-1.0.2-1-g032ef57-signed-testing.xpi.zip](https://github.com/mozilla/doh-rollout/files/3779768/doh_roll-out-1.0.2-1-g032ef57-signed-testing.xpi.zip)

Be sure to set `xpinstall.signatures.dev-root` to `true` when testing with this file.

File: src/background.js [hunk 1]
```diff
@@ -367,6 +367,7 @@ const setup = {
       log("Disabling"); 
       browser.storage.local.clear();
       await stateManager.setState("disabled");
```
Comment (nhi-nguyen) [inline src/background.js]: this will add back `doh-rollout.previous.trr.mode` via rememberTRRMode(). I'm not sure we need to clear the `doh-rollout.*` prefs if we're adding a few back.
