### PR TITLE
Fixed #185 - Clear `doh-rollout.self-enabled` pref faster

### LINKED ISSUE #184: The "doh-rollout.self-enabled" pref is not removed after changing the "network.trr.mode" pref value via “about:preferences#networking” page
**[Affected Platforms]:**
- All Windows

**[Affected Versions]:**
- Firefox Release 70.0.1, Build ID 20191030021342
 
**[Prerequisites]:**
- Have an active Normandy [testing recipe ](https://delivery-console.stage.mozaws.net/recipe/878/)for DoH.
- You are enrolled in the Treatment branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:preferences#networking" page.
3. Click the "Settings" button and uncheck the "Enable DNS over HTTPS" checkbox.
4. Click the "OK" button.
5. Restart the browser.
6. Observe if the "doh-rollout.self-enabled" preference is removed.

**[Expected result]:**
- The "doh-rollout.self-enabled" pref is removed.

**[Actual result]:**
- The "doh-rollout.self-enabled" pref is displayed.

**[Notes]:**
- The issue is not reproducible when the user chooses to opt-out from the experiment through the DoH doorhanger.
- I have attached a screen recording of the issue:

self pref

### LINKED ISSUE #185: The "doh-rollout.self-enabled" pref is not removed after disabling DNS from “about:preferences” page and reconnecting to the network twice
**[Affected Platforms]:**
- All Windows

**[Affected Versions]:**
- Firefox Release 70.0.1, Build ID 20191030021342
 
**[Prerequisites]:**
- Have an active Normandy testing recipe for DoH.
- You are enrolled in the Treatment branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:preferences#networking" page.
3. Click the "Settings" button and uncheck the "Enable DNS over HTTPS" checkbox.
4. Click the "OK" button.
5. Disconnect and reconnect to the network twice.
6. Wait for 60 seconds and navigate to "about:config".
7. Verify that the "doh-rollout.self-enabled" is removed.

**[Expected result]:**
- The "doh-rollout.self-enabled" pref is removed.

**[Actual result]:**
- The "doh-rollout.self-enabled" pref remains set as "true".

**[Notes]:**
- The "doh-rollout.self-enabled" pref is not removed even after you restart the browser after performing the steps above.
- This issue is not reproducible when restarting the browser twice instead of network reconnection.
- I have made a screen recording of the issue: https://tinyurl.com/vbnm96g.

### PR DESCRIPTION
**Pull request by maxxcrawford**
Also improves/resolves #184 

- Moved the logic to clear `doh-rollout.self-enabled` pref to occur at any event that should disable heuristics. ~at the same time as the `rememberDisableHeuristics()` is ran.~ This will remove the additional step of restarting the browser a SECOND time to clear the pref. 

Expected behavior: 

1. Enable add-on, turn on DoH via heuristics 
1. Manually modify your DoH settings via about:preferences#networking (Uncheck DoH)
1. Trigger heuristics check by restarting browser OR change network. 
1. Confirm that the pref, `doh-rollout.self-enabled` has no value. 

_Note that changing your network connect takes at least 60s to fire (after switching networks)._

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -239,13 +240,25 @@ const rollout = {
 
     switch (typeof defaultValue) {
     case "boolean":
-      log("boolean", name, await browser.experiments.preferences.getBoolPref(name, defaultValue));
+      log({
+        "type": "boolean",
```
Comment (nhnt11) [inline src/background.js]: nit: no need for quotes around the keys in this object.

File: src/background.js [hunk 2]
```diff
@@ -239,13 +240,25 @@ const rollout = {
...
+        "name": name,
```
Comment (nhnt11) [inline src/background.js]: nit: this can just be `name` ("shorthand property names" in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer)

File: src/background.js [hunk 3]
```diff
@@ -90,6 +90,7 @@ const stateManager = {
 
   async rememberDisableHeuristics() {
     log("Remembering to never run heuristics again");
+    browser.experiments.preferences.clearUserPref(DOH_SELF_ENABLED_PREF);
```
Comment (nhnt11) [inline src/background.js]: Is this the right place to do this? I'd prefer clearing this pref in the code that actually handles the event. We don't want to make a function called `rememberDisableHeuristics` responsible for more than its job description.

Comment (maxxcrawford) [reply src/background.js]: @nhnt11 I don't think it is after consideration. I moved the clear pref call to occur where that function is called, rather than add it to the function. Thanks!

Comment (nhnt11) [reply src/background.js]: The new call site looks good, thanks!
