### PR TITLE
Address v1.2 Issues

### LINKED ISSUE #194: Disable Pocket policy is not seen as active after disconnecting and reconnecting to the network
**[Affected Platforms]:**
- Windows 10x64
- Windows 7x64
- macOS 10.15
- Ubuntu 18.04x64

**[Affected Versions]:**
- Firefox Release 71.0
- Firefox Beta 71.0b12
- Firefox Nightly 72.0a1 (BuildID 20191127114233)

**[Prerequisites]:**
- Have an active Normandy testing [recipe](https://delivery-console.stage.mozaws.net/recipe/880/) for DoH.
- You are enrolled in the Treatment branch.
- Add the policies.json in the firefox/distribution folder with the following content:
{
  "policies": {
    "DisablePocket": true
  }
}

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to about:config and add *doh-rollout.enabled* to *true*.
3. Go to about:telemetry#events-tab.
4. **Disconnect** from network and **reconnect**.
5. Wait ~1min and refresh the about:telemetry#events-tab page.

**[Expected result]:**
- Doorhanger isn't displayed and telemetry event with **Value**  *policy_without_doh* is recevied.

**[Actual result]:**
- Doorhanger is displayed and telemetry event doesn't see the policie as enabled.

**[Notes]:**
- The issue is reproducible with the 1.2.0rc2 version of the add-on.
- I have attached a screenshot of the issue:
Untitled1

### PR DESCRIPTION
**Pull request by maxxcrawford**
Addresses the following issues: 

- #194 - Added logic to skip heuristics check on network change

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -469,33 +445,14 @@ const rollout = {
...
-    // If the captive portal is already unlocked or doesn't exist,
-    // run the measurement
-    let captiveState = await browser.captivePortal.getState();
-    log("Captive state:", captiveState);
-    if ((captiveState === "unlocked_portal") ||
-        (captiveState === "not_captive")) {
-      await rollout.onReady({state: captiveState});
-    }
+    browser.captivePortal.onConnectivityAvailable.addListener(
+      rollout.runStartupHeuristics()
```
Comment (nhnt11) [inline src/background.js]: The return value of this call (which is a promise), is passed to `addListener`, which expects a function.
You either want to wrap this call in an anonymous function, or pass the function handle without calling it.
I recommend the former, because if you just pass the function handle, the function's scope will not have access to the same `this` which can lead to bugs (you'd need to call bind() to make that work)

File: src/background.js [hunk 2]
```diff
@@ -444,11 +422,8 @@ const rollout = {
     let skipHeuristicsCheck = await rollout.getSetting(DOH_SKIP_HEURISTICS_PREF, false);
     log("skipHeuristicsCheck: ", skipHeuristicsCheck);
 
-    if (!skipHeuristicsCheck) {
-      let shouldRunHeuristics = await stateManager.shouldRunHeuristics();
-      if (shouldRunHeuristics) {
-        await rollout.main();
-      }
+    if (!skipHeuristicsCheck && ( await stateManager.shouldRunHeuristics() )) {
```
Comment (nhnt11) [inline src/background.js]: nit: no whitespace padding inside the parentheses

File: src/background.js [hunk 3]
```diff
@@ -451,33 +448,14 @@ const rollout = {
...
-    // run the measurement
-    let captiveState = await browser.captivePortal.getState();
-    log("Captive state:", captiveState);
-    if ((captiveState === "unlocked_portal") ||
-        (captiveState === "not_captive")) {
-      await rollout.onReady({state: captiveState});
-    }
+    browser.captivePortal.onConnectivityAvailable.addListener(
+      rollout.runStartupHeuristics()
+    );
```
Comment (ddragana) [inline src/background.js]: Also adding only this listener is not enough. If we already have connectivity it will never fire, until we lose connectivity and get it back again.
You will need to check browser.captivePortal.getState() as well.

On every network change event we should check captive portal as well.

File: src/background.js [hunk 4]
```diff
@@ -469,33 +445,19 @@ const rollout = {
...
+    });
 
-    // Only proceed if we're not behind a captive portal
-    if ((details.state !== "unlocked_portal") &&
-        (details.state !== "not_captive")) {
-      return;
-    }
+  },
 
+  async runStartupHeuristics() {
```
Comment (nhnt11) [inline src/background.js]: Please move the `shouldRunHeuristics` and `skipHeuristicsCheck` logic into this function, it's duplicated in every call site.

File: src/background.js [hunk 5]
```diff
@@ -469,33 +445,19 @@ const rollout = {
         }
       }
```
Comment (nhnt11) [inline src/background.js]: This is pretty much duplicated in `runStartupHeuristics`.
I suggest moving this block of code into the `heuristics` function and renaming it `runHeuristics` or something.

File: src/background.js (hunk 3 above)
Comment (nhnt11) [reply src/background.js]: This is fired when the network changes, once connectivity has been established. The propagated status is "clear".

Comment (nhnt11) [reply src/background.js]: I suggested to Maxx that we should just not bother with network changes at all. The captive portal service takes care of establishing connectivity.
If we want to be super thorough, we'd have to check whether the user has disabled captive portal for some reason, and only in that case, check the network status as a fallback.

Comment (nhnt11) [reply src/background.js]: (you're right that we would have to check the captive portal state on the first run though)

Comment (nhnt11) [reply src/background.js]: The network change debouncing and the captive portal logic are likely to conflict in weird ways. This needs to be pretty thoroughly tested. Ideally what we'd do is set and save a timeout when the network changes, and after that timeout, run heuristics. If we get a captive portal "clear" or "not_captive", we'd clear the timeout and run heuristics immediately. If we get a captive portal "captive", we'd clear the timeout and wait for a "clear" or "not_captive". If we get a link "down", we'd clear the timeout and wait for link "up".

Comment (nhnt11) [reply src/background.js]: This conflict wasn't apparent before because the captive portal logic was simply not running.

File: src/background.js (hunk 5 above)
Comment (maxxcrawford) [reply src/background.js]: Great note. Updated!

File: src/background.js (hunk 4 above)
Comment (maxxcrawford) [reply src/background.js]: Done.

File: src/background.js (hunk 3 above)
Comment (maxxcrawford) [reply src/background.js]: @ddragana @nhnt11 I'm getting duplicate events on start up. Once, officially for "startup" and another when onConnectivityAvailable fires. Can I expect that onConnectivityAvailable fires once on start up?

Comment (ddragana) [reply src/background.js]: I looked at m.-c. code and I do not find "startup" event, but maybe I just missed it somehow. 
Anyway do not relay on that, it may be racy.

File: src/background.js [hunk 6]
```diff
@@ -422,47 +422,33 @@ const rollout = {
     let skipHeuristicsCheck = await rollout.getSetting(DOH_SKIP_HEURISTICS_PREF, false);
```
Comment (ddragana) [inline src/background.js]: This line is not needed, or we just want to log the value. Anyway the comment is wrong.

File: src/background.js [hunk 7]
```diff
@@ -422,47 +422,33 @@ const rollout = {
...
-    await rollout.runStartupHeuristics();
-
-
+    await rollout.runHeuristics("startup");
 
     // Listen for network change events to run heuristics again
     browser.experiments.netChange.onConnectionChanged.addListener(async () => {
       log("onConnectionChanged");
+      rollout.runHeuristics("netChange");
       // Only run the heuristics if user hasn't explicitly enabled/disabled DoH
```
Comment (ddragana) [inline src/background.js]: remove the comment

File: src/background.js [hunk 8]
```diff
@@ -422,47 +422,33 @@ const rollout = {
     let skipHeuristicsCheck = await rollout.getSetting(DOH_SKIP_HEURISTICS_PREF, false);
     log("skipHeuristicsCheck: ", skipHeuristicsCheck);
 
-    await rollout.runStartupHeuristics();
-
-
+    await rollout.runHeuristics("startup");
```
Comment (ddragana) [inline src/background.js]: This is not really correct:
 First (before this line) add  browser.experiments.netChange.onConnectionChanged listener,
Second add browser.captivePortal.onConnectivityAvailable listener.
The two listeners are correct.
call  await rollout.runHeuristics("startup"); . 
The "startup" and "netChange" needs to be removed, they need to be detected in a different way.

runHeuristics function should check for network and captive portal state before doing anything and if If nsINetworkLinkService.linkStatusKnown or nsINetworkLinkService.isLinkUp is false or browser.captivePortal.getState() is not  neither "unlocked_portal" nor "not_captive exit without running heuristics.  We have setup listeners for the network-change events and the captive portal events and they will trigger a new runHeuristics.

This code may run multiple heuristics in parallel. That is fine, but we need to make sure to disable/enable TRR only when the results of the runHeuristics that is triggered the last are ready and ignore results of other runHeuristics

File: src/background.js (hunk 3 above)
Comment (valenting) [reply src/background.js]: I don't know if using the captive portal event is advisable - there are a few weird types of captive portals that we don't actually detect - and the CP web-extension API is quite new and I'm not sure we can be 100% sure there are now bugs.
Maybe we should keep the network change events as well for the time?

Comment (nhnt11) [reply src/background.js]: Not detecting a portal is fine, IMO. We still receive the connectivity event. The detection checks the availability of a canonical URL, which is perfect for our use case no? Do we care about the portals we don't manage to detect? There's no way to handle those anyway.

I am confident that if the captive portal service is enabled, it's redundant to check both network changes and portal connectivity. We'll just end up building a complicated state machine to handle the race.

Comment (nhnt11) [reply src/background.js]: If on the other hand you are referring to a timeout or abort of the portal check, to me that's still good indication that we shouldn't run heuristics.

Comment (nhnt11) [reply src/background.js]: Dragana, Valentin, Maxx, and I came to a conclusion outside of this thread:

1. Check network state and captive portal state. If network up and not captive, run heuristics.
2. Add listener for network ID change. When it changes, run heuristics. Listen for captive portal state change.
    a. If we get a locked portal, wait for clear, then run heuristics again. The previous run would have been unsuccessful.
    b. If we get a clear portal, then all is well.

**Comment by maxxcrawford** [comment]
Revised the captive portal logic to [mirror what was done](https://searchfox.org/mozilla-central/source/browser/extensions/doh-rollout/background.js#457-504) on Mozilla Central. Note that there are some differences, as the 60s timeout logic remains in the `/expermients/netChange api`, rather than in the background script.

File: src/background.js [hunk 9]
```diff
@@ -444,60 +422,61 @@ const rollout = {
...
+        log("No network fluctuation for 60 seconds, running heuristics.");
+        // Only run the heuristics if user hasn't explicitly enabled/disabled DoH
+        let shouldRunHeuristics = await stateManager.shouldRunHeuristics();
+
+        if (!shouldRunHeuristics) {
+          return;
+        }
+
+        // Only run the heuristics if user hasn't explicitly enabled/disabled DoH
+        rollout.runHeuristics("netChange");
```
Comment (nhnt11) [inline src/background.js]: We need to set `rollout.networkSettledTimeout = null;` here as well (no need to `clearTimeout()` though since we're in the callback already.)

**Comment by maxxcrawford** [comment]
Reverted all Captive Portal commits to a different branch/PR #207.
