### PR TITLE
Fixed #88 - Refactored sleep function in onConnectionChanged event

### LINKED ISSUE #88: I think sleep does not work correctly
https://github.com/mozilla/doh-rollout/blob/8e9c779ce64bc98eefc529f862a9ed463a15ace2/src/experiments/netChange/api.js#L33-L46

The code is calling fire.async(data); on every change event instead of calling it only once in 5s. For every event it does a sleep and calls fire.async(data).

I think we should do something in this direction:

```
            let observer = async (subject, topic, data) => {
                  // if we get "up" event we should fire an event.
                  if (data === "up") {
                    last_even = now();
                    fire.async(data);
                  }

                  if (data === "changed") {
                    // We will coalesce event that are less than 5s apart. 
                    if ((now() - last_event > 5000) &&
                         gNetworkLinkService.linkStatusKnown &&
                        gNetworkLinkService.isLinkUp) {
                      last_even = now();
                      fire.async(data);
                   }
                }
              };
```

Looking at the code we will send network change event before a "up" event.
https://searchfox.org/mozilla-central/source/netwerk/system/win32/nsNotifyAddrListener.cpp#686

[Only a note: In necko, we coalesce event that are happening in 1second as well:
https://searchfox.org/mozilla-central/source/netwerk/system/win32/nsNotifyAddrListener.cpp#439]

Or other version with sleep:

```
            let observer = async (subject, topic, data) => {
                  if (already_waiting == false) {
                    if (data === "changed" || data === "up") {
                      already_waiting = true;
                      await sleep(5000);
                      
                      if (gNetworkLinkService.linkStatusKnown &&
                         gNetworkLinkService.isLinkUp) {
                        fire.async(data);
                      }
                      already_waiting = false;
                    }
                 }
              };
```

### PR DESCRIPTION
**Pull request by maxxcrawford**
This change will only check for "up" after a  "changed" event once each 5 seconds while reconnecting to networks.

### CODE REVIEW

File: src/experiments/netChange/api.js [hunk 1]
```diff
@@ -30,20 +31,21 @@ var netChange = class netChange extends ExtensionAPI {
...
-                  // isn't quite up yet. We should wait before running the 
-                  // heuristics to ensure the network is up.
-                  await sleep(5000);
-  
-                  // After sleeping, check the connection again
-                  if (gNetworkLinkService.linkStatusKnown &&
-                      gNetworkLinkService.isLinkUp &&
-                      data === "changed") {
+                  // We will coalesce event that are less than 5s apart.
+                  if ( Date.now() - last_event > 5000 &&  gNetworkLinkService.linkStatusKnown && gNetworkLinkService.isLinkUp) {
```
Comment (jonathanKingston) [inline src/experiments/netChange/api.js]: nit space
